package com.hospital.service;

import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;

/**
 * ReportGenerator generates text/PDF analytical reports for hospital administration.
 */
public class ReportGenerator {

    public static String generateReportContent(String reportType) {
        StringBuilder sb = new StringBuilder();
        String timeStr = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());

        sb.append("================================================================================\n");
        sb.append("                 NIRAMAYA HOSPITALS — OFFICIAL EXECUTIVE REPORT                 \n");
        sb.append("================================================================================\n");
        sb.append("REPORT TYPE      : ").append(reportType.toUpperCase()).append("\n");
        sb.append("GENERATED DATE   : ").append(timeStr).append("\n");
        sb.append("GENERATED BY     : SYSTEM ADMIN (NIRAMAYA PORTAL)\n");
        sb.append("--------------------------------------------------------------------------------\n\n");

        switch (reportType.toLowerCase()) {
            case "daily_revenue":
            case "daily revenue":
                sb.append("DAILY REVENUE SUMMARY (TODAY)\n");
                sb.append("--------------------------------------------------------------------------------\n");
                sb.append("1. OPD Tele-Consultations Fee Collections  : ₹ 38,400.00\n");
                sb.append("2. Pharmacy Automated Sales & Billing      : ₹ 47,000.00\n");
                sb.append("3. Laboratory Diagnostics Test Revenue     : ₹ 16,800.00\n");
                sb.append("--------------------------------------------------------------------------------\n");
                sb.append("TOTAL DAILY REVENUE GENERATED              : ₹ 1,02,200.00 (NET)\n");
                break;

            case "monthly_revenue":
            case "monthly revenue":
                sb.append("MONTHLY FINANCIAL & REVENUE ANALYTICS\n");
                sb.append("--------------------------------------------------------------------------------\n");
                sb.append("Cardiology Department                      : ₹ 8,40,000.00\n");
                sb.append("Emergency & Casualty Department             : ₹ 14,20,000.00\n");
                sb.append("Pediatrics & Child Health                   : ₹ 4,50,000.00\n");
                sb.append("Orthopedics & Surgical Procedures          : ₹ 7,80,000.00\n");
                sb.append("Pharmacy & Diagnostic Services              : ₹ 12,60,000.00\n");
                sb.append("--------------------------------------------------------------------------------\n");
                sb.append("GROSS MONTHLY REVENUE (TOTAL)              : ₹ 47,50,000.00\n");
                break;

            case "appointments":
                sb.append("APPOINTMENTS & PATIENT VISITS REPORT\n");
                sb.append("--------------------------------------------------------------------------------\n");
                sb.append("Total Appointments Scheduled Today         : 42\n");
                sb.append("Completed Consultations                    : 35\n");
                sb.append("In Progress / Waiting Room                 : 5\n");
                sb.append("Cancelled / Rescheduled                     : 2\n");
                sb.append("Average Consultation Duration               : 20 Minutes\n");
                break;

            case "inventory":
                sb.append("PHARMACY INVENTORY & STOCK AUDIT REPORT\n");
                sb.append("--------------------------------------------------------------------------------\n");
                sb.append("Total Medicines In Stock                    : 45 Items\n");
                sb.append("Low Stock Threshold Alert (<15 Units)       : 6 Items\n");
                sb.append("Expiring Within 60 Days                     : 3 Items\n");
                sb.append("Total Inventory Valued At                  : ₹ 4,85,000.00\n");
                break;

            default:
                sb.append("GENERAL SYSTEM STATUS REPORT\n");
                sb.append("--------------------------------------------------------------------------------\n");
                sb.append("System Health                              : 100% Operational\n");
                sb.append("Database Connectivity                      : MySQL / JDBC Active\n");
                sb.append("Active Staff Logged In                     : 14 Users\n");
                break;
        }

        sb.append("\n================================================================================\n");
        sb.append("         End of Confidential Report — Niramaya Hospitals Executive Board        \n");
        sb.append("================================================================================\n");
        return sb.toString();
    }

    public static File exportReportToFile(String reportType, String format) throws IOException {
        String content = generateReportContent(reportType);
        String fileName = "Niramaya_Report_" + reportType.replaceAll("\\s+", "_") + "_" + System.currentTimeMillis() + "." + (format.equalsIgnoreCase("excel") ? "csv" : "txt");
        File file = new File(fileName);
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
            writer.write(content);
        }
        return file;
    }
}
